version: "3.5"

services:
    nginx:
        image: "nginx"
        container_name: "nginx"
        restart: "unless-stopped"
        ports:
            - 8080:80
        volumes:
            - type: "bind"
              source: "${NGINX_LOG_DIR:-./mounts/nginx/log}"
              target: "/var/log/nginx"

networks:
    default:
        driver: "bridge"
        name: "logstash_bridge"
