version: "3.5"

services:
    logstash:
        container_name: "logstash"
        restart: "unless-stopped"
        build:
            context: "containers/logstash"
            args:
                PLUGIN_FULL_NAME: "${PLUGIN_FULL_NAME}"
                PLUGIN_PATH: "/home/logstash/plugins/${PLUGIN_FULL_NAME}"
        command: --enable-local-plugin-development --debug
        networks:
            logstash_bridge:
                aliases:
                    - "logstash.local"
        ports:
            - 5044:5044
            - 9600:9600
            - 9999:9999
        volumes:
            - type: "bind"
              source: "${PLUGIN_HOME:-./mounts/logstash-plugin}"
              target: "/home/logstash/plugins/${PLUGIN_FULL_NAME}"
            - type: "bind"
              source: "${LOGSTASH_PIPELINE:-./mounts/logstash/pipeline}"
              target: "/usr/share/logstash/pipeline"
    nginx:
        image: "nginx"
        container_name: "nginx"
        restart: "unless-stopped"
        networks:
            logstash_bridge:
        ports:
            - 8080:80
        volumes:
            - type: "bind"
              source: "${NGINX_LOG_DIR:-./mounts/nginx/log}"
              target: "/var/log/nginx"
    beats:
        image: "docker.elastic.co/beats/filebeat:8.6.1"
        container_name: "beats"
        restart: "unless-stopped"
        networks:
            logstash_bridge:
        volumes:
            - type: "bind"
              source: "${NGINX_LOG_DIR:-./mounts/nginx/log}"
              target: "/logs/nginx"
            - type: "bind"
              source: "${BEATS_CONFIG:-./mounts/beats/filebeat.docker.yml}"
              target: "/usr/share/filebeat/filebeat.yml"
              read_only: true
    idmefv2javaserver:
        image: "fdshell/idmefv2java"
        container_name: "idmefv2javaserver"
        restart: "unless-stopped"
        networks:
            logstash_bridge:
        ports:
            - 9999:9999
        command: "./server.sh --port 9999"
    idmefv2javaclient:
        image: "fdshell/idmefv2java"
        container_name: "idmefv2javaclient"
        restart: "unless-stopped"
        networks:
            logstash_bridge:
        command: "./client.sh --server ${JAVA_SERVER_HOST} --retry 1000 --delay 5000"

networks:
    logstash_bridge:
        driver: "bridge"
