version: "3.5"

services:
    logstash:
        container_name: "logstash"
        restart: "unless-stopped"
        build:
            context: "containers/logstash"
            args:
                PLUGIN_GEMSPEC: "${PLUGIN_GEMSPEC}"
        command: sleep 1d
        networks:
            default:
                aliases:
                    - "logstash.local"
        ports:
            - 5044:5044
            - 9600:9600
        volumes:
            - type: "bind"
              source: "${PLUGIN_HOME:-./mounts/logstash-plugin}"
              target: "/home/logstash-plugin"
            - type: "bind"
              source: "${LOGSTASH_PIPELINE:-./mounts/logstash/pipeline}"
              target: "/usr/share/logstash/pipeline"

networks:
    default:
        driver: "bridge"
        name: "logstash_bridge"
