version: "3.5"

services:
    beats:
        image: "docker.elastic.co/beats/filebeat:8.6.1"
        container_name: "beats"
        restart: "unless-stopped"
        networks:
            logstash_bridge:
        volumes:
            - type: "bind"
              source: "${NGINX_LOG_DIR:-./mounts/nginx/log}"
              target: "/logs/nginx"
            - type: "bind"
              source: "${BEATS_CONFIG:-./mounts/beats/filebeat.docker.yml}"
              target: "/usr/share/filebeat/filebeat.yml"
              read_only: true

networks:
    logstash_bridge:
        driver: "bridge"
