version: "3.5"

services:
    logstash:
        container_name: "logstash"
        restart: "unless-stopped"
        build:
            context: "containers/logstash"
        networks:
            default:
                aliases:
                    - "logstash.local"
        ports:
            - 5044:5044
            - 9600:9600
        volumes:
            - type: "bind"
              source: "${LOGSTASH_PLUGIN_HOME:-./mounts/logstash-plugin}"
              target: "/home/logstash-plugin"

networks:
    default:
        driver: "bridge"
        name: "logstash_bridge"
