version: "3.5"

services:
    logstash:
        container_name: "logstash"
        restart: "unless-stopped"
        build:
            context: "containers/logstash"
        #command: sleep 1d
        networks:
            logstash_bridge:
                aliases:
                    - "logstash.local"
        ports:
            - 5044:5044
            - 9600:9600
        volumes:
#            - type: "bind"
#              source: "${PLUGIN_HOME:-./mounts/logstash-plugin}"
#              target: "/home/logstash-plugin"
            - type: "bind"
              source: "${LOGSTASH_PIPELINE:-./mounts/logstash/pipeline}"
              target: "/usr/share/logstash/pipeline"
    nginx:
        image: "nginx"
        container_name: "nginx"
        restart: "unless-stopped"
        networks:
            logstash_bridge:
        ports:
            - 8080:80
        volumes:
            - type: "bind"
              source: "${NGINX_LOG_DIR:-./mounts/nginx/log}"
              target: "/var/log/nginx"
    beats:
        image: "docker.elastic.co/beats/filebeat:8.6.1"
        container_name: "beats"
        restart: "unless-stopped"
        networks:
            logstash_bridge:
        volumes:
            - type: "bind"
              source: "${NGINX_LOG_DIR:-./mounts/nginx/log}"
              target: "/logs/nginx"
            - type: "bind"
              source: "${BEATS_CONFIG:-./mounts/beats/filebeat.docker.yml}"
              target: "/usr/share/filebeat/filebeat.yml"
              read_only: true

networks:
    logstash_bridge:
        driver: "bridge"
